### ISSUE TITLE
Add ReadTheDocs config file

### ISSUE THREAD

**Issue by robintw** [EOA-team/PyProSAIL#3]
Hi - I'm Robin, the original author of PyProSAIL. I seem to still be the admin for the ReadTheDocs project which hosts the docs for this (we should probably change that).

I've had an email from ReadTheDocs saying that we need to add a ReadTheDocs config file to make the docs continue building. Are you able to do this? Or do you want me to?

It might be easiest if I made you a maintainer on RtD and then you can deal with any issues that occur - can you send your ReadTheDocs username and I'll add you as a maintainer.

**Comment by lukasValentin** [comment]
Hi @robintw, sorry for not spotting this issue earlier - my username is the same as my Github name: so it's lukasValentin

**Comment by lukasValentin** [comment]
I'm planning to add a python_app.yaml file anyways to test the package automatically using Github workflows so I guess this is also the place where I'd add a process to keep ReadtheDocs updated

**Comment by robintw** [comment]
Thanks, I've added you as a maintainer.
